### ISSUE TITLE
Refactoring large methods

### ISSUE THREAD

**Issue by jerryjohnjacob** [shshamim63/Payment_calculator#4]
What would be a good way to refactor the `final_payment_list` method in the `Payment` model? It is rather long now.

**Comment by shshamim63** [comment]
Yes, the method is long. Thanks for notifying me. Well, I can separate the method into two Payment class methods, let's say interest_only_payments, regular_payment.  They will return two arrays. To get the final output can merge two arrays into one.
```ruby
def self.interest_only_payments(...)
end

def self.regular_payments(...)
end

def self.final_payment_list
  interest_only_payments(...) + regular_payments(...)
end
```

**Comment by jerryjohnjacob** [comment]
That's a valid way, sure. Can you think of one that also increases efficiency? There might literally be no observable performance gain given modern computing speeds, but let's just explore the path.

**Comment by jerryjohnjacob** [comment]
That's one way for sure. Can you think of one that also reduces the number of independent loops that are there now?

**Comment by shshamim63** [comment]
Hey @jerryjohnjacob , I have opened a PR to resolve the addressed issues. You can review or comment [here](https://github.com/shshamim63/Payment_calculator/pull/5)
